version: '3.1'

services:

  mongo:
    build:
      context: ./backend/database
      dockerfile: Dockerfile.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"