version: '3.1'

services:

  mongo:
    build:
      context: ./backend/database
      dockerfile: Dockerfile.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend/server
      dockerfile: Dockerfile.dev
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://root:example@mongo:27017/mydatabase
    ports:
      - "8080:8080"
    depends_on:
      - mongo
